#!/bin/bash
# Copyright (C) 2008 University of Louisiana at Lafayette
# Authors: Mark McKelvy

script_name=`basename ${0}`
source $CBSUPPORT/lite_scripts/lite_cfg

shutdown(){
    echo "Shutting down..."
    case "$venue" in
	flex)
	    pkill start_simulator
	    sleep 1
	    stop_testing_sequence;;
	cluster.tis)
	    for machine in $tis_machine_list ; do
		ssh $machine "pkill start_simulator; sleep 1; stop_testing_sequence;" &
	    done
	    pkill start_simulator
	    sleep 1
	    stop_testing_sequence
	    wait;;
	standalone)
	    for machine in $tis_machine_list ; do
		ssh $machine "pkill start_simulator; sleep 1; stop_testing_sequence;" &
	    done
	    pkill start_simulator
	    sleep 1
	    stop_testing_sequence
	    wait;;
    esac
    echo "done"
}

show_options(){
    #Add displayable options here
    echo
    echo "This script is used for stopping the simulation in the lite center."
    echo
    echo "Usage: $script_name"
    echo
    exit
}

get_options(){
    #Catch arguments here
    if [ "$1" == "-?" ] ; then
	show_options
    fi
}

set_defaults(){
    venue=$LITE_VENUE
    lite_cfg=$CBSUPPORT/lite_scripts/lite_cfg

    case "$venue" in
	flex) ;;
	cluster.tis)
	    tis_machine_list="ws1 ws2 ws3 ws4 ws5";;
	standalone)
	    tis_machine_list="tiscluster1 tiscluster2 tiscluster3 tiscluster4 tiscluster5 tiscluster6";;
	*)
	    echo "($script_name) error: incorrect venue set - $venue."
	    exit -1;;
    esac
}

sanity_check(){
    if [ "$venue" != "flex" -a \
	"$venue" != "cluster.tis" -a \
	"$venue" != "standalone" ] ; then
	echo "($script_name) error: incorrect venue set - $venue."
	exit -1
    fi

    source $lite_cfg
    if [ ! -n "$VJ_BASE_DIR" -o ! -n "$VJ_CFG_PATH" ] ; then
	echo "($script_name) error: VJ_BASE_DIR or VJ_CFG_PATH not set."
	exit -1
    fi
}

set_defaults $*
get_options $*
sanity_check $*

shutdown
