#!/bin/bash
# Copyright (C) 2008 University of Louisiana at Lafayette
# Authors: Mark McKelvy

script_name=`basename ${0}`
source $CBSUPPORT/lite_scripts/lite_cfg
source $CBSUPPORT/lite_scripts/lite_hosts

shutdown(){
    lite_stop_simulation
}

show_options(){
    #Add displayable options here
    echo
    echo "This script is used for starting up simulation in lite center."
    echo
    echo "Usage: $script_name <start_simulator_opts>"
    echo
    exit
}

get_options(){
    #Catch arguments here
    if [ "$1" == "-?" ] ; then
	show_options
    fi
}

set_defaults(){
    :
}

sanity_check(){
    if [ "$venue" != "flex" -a \
	"$venue" != "cluster.tis" -a \
	"$venue" != "standalone" -a \
	"$venue" != "theater" ] ; then
	echo "($script_name) error: incorrect venue set - $venue."
	exit -1
    fi

    if [ ! -d "$CBSUPPORT" ] ; then
	echo "($script_name) error: can't find cbsupport=$CBSUPPORT"
	exit -1
    fi

    if [ ! -n "$VJ_BASE_DIR" -o ! -n "$VJ_CFG_PATH" ] ; then
	echo "($script_name) error: VJ_BASE_DIR or VJ_CFG_PATH not set."
	exit -1
    fi
}

start_simulation(){
    #kill running programs on other machines
    for machine in $machine_list ; do
	ssh $machine "stop_testing_sequence; clean_shared_mem" &
	echo "ssh $machine \"stop_testing_sequence; clean_shared_mem\" &"
    done
    stop_testing_sequence
    clean_shared_mem
    wait

    #setup cbviz options
    cbviz_opts=
    while getopts "c:k:I:r:V:a:b:Bd:D:fg:I:Lm:MN:oO:p:PR:t:u:vw:xX?"\
	option; do
	case "$option" in
	    c) cbviz_opts="$cbviz_opts -c $OPTARG";;
	    k) cbviz_opts="$cbviz_opts -l $OPTARG";;
	    I) cbviz_opts="$cbviz_opts -i $OPTARG";;
	    r) cbviz_opts="$cbviz_opts -N $OPTARG";;
	    V) cbviz_opts="$cbviz_opts -v $OPTARG";;
	    *) echo "Skipping '$option $OPTARG' for cbviz.";;
	esac
    done

    #start local simulation
    echo "cbviz_opts=$cbviz_opts"
    echo "start_simulator $* -D $CB_DATA_NET &"
    start_simulator $* -D $CB_DATA_NET &
    sleep 4

    #start remote display
    for machine in $machine_list ; do
	ssh $machine "source ~/.bashrc; source $CBSUPPORT/lite_scripts/lite_cfg; cb_remote" &
	ssh $machine "source ~/.bashrc; source $CBSUPPORT/lite_scripts/lite_cfg; export VPR_DEBUG_NFY_LEVEL=0; cbviz -m simulation $cbviz_opts" &
    done
}

set_defaults $*
get_options $*
sanity_check $*

start_simulation $*

