#!/bin/bash
# Copyright (C) 2008 University of Louisiana at Lafayette
# Authors: Mark McKelvy

script_name=`basename ${0}`
source $CBSUPPORT/lite_scripts/lite_cfg
source $CBSUPPORT/lite_scripts/lite_hosts

shutdown(){
    echo "Shutting down..."
    for machine in $machine_list ; do
	ssh $machine "pkill start_simulator; sleep 1; stop_testing_sequence;" &
    done
    pkill start_simulator
    sleep 1
    stop_testing_sequence
    wait
    echo "done"
}

show_options(){
    #Add displayable options here
    echo
    echo "This script is used for stopping the simulation in the lite center."
    echo
    echo "Usage: $script_name"
    echo
    exit
}

get_options(){
    #Catch arguments here
    if [ "$1" == "-?" ] ; then
	show_options
    fi
}

set_defaults(){
    :
}

sanity_check(){
    :
}

set_defaults $*
get_options $*
sanity_check $*

shutdown
