#!/bin/bash
# Copyright (C) 2009 University of Louisiana at Lafayette
# Authors: Mark McKelvy

script_name=`basename ${0}`
source $CBSUPPORT/lite_scripts/lite_cfg
source $CBSUPPORT/lite_scripts/lite_hosts

shutdown(){
    lite_stop_simulation
}

show_options(){
    #Add displayable options here
    echo
    echo "This script is used for starting up visualization in lite center."
    echo
    echo "Usage: $script_name <cbviz_opts>"
    echo
    echo "<cbviz_opts>:"
    cbviz -?
    echo
    exit
}

get_options(){
    #Catch arguments here
    if [ "$1" == "-?" ] ; then
	show_options
    fi
}

set_defaults(){
    :
}

sanity_check(){
    if [ "$venue" != "flex" -a \
	"$venue" != "cluster.tis" -a \
	"$venue" != "standalone" -a \
	"$venue" != "theater" ] ; then
	echo "($script_name) error: incorrect venue set - $venue."
	exit -1
    fi

    if [ ! -d "$CBSUPPORT" ] ; then
	echo "($script_name) error: can't find cbsupport=$CBSUPPORT"
	exit -1
    fi

    if [ ! -n "$VJ_BASE_DIR" -o ! -n "$VJ_CFG_PATH" ] ; then
	echo "($script_name) error: VJ_BASE_DIR or VJ_CFG_PATH not set."
	exit -1
    fi
}

clean_shared_mem_all(){
    for machine in $machine_list ; do
	ssh $machine "clean_shared_mem" &
	echo "ssh $machine \"clean_shared_mem\" &"
    done
    clean_shared_mem
    wait
}

start_visualization(){
    #kill running programs on other machines
    clean_shared_mem_all
    for machine in $machine_list ; do
	ssh $machine "stop_testing_sequence;" &
	echo "ssh $machine \"stop_testing_sequence;\" &"
    done

    #setup cbviz options
    cbviz_opts=$*

    #start local simulation
#    echo "cbviz $cbviz_opts &"
#    cbviz $cbviz_opts &
#    sleep 4

    #start remote display
    for machine in $machine_list ; do
	ssh $machine "source ~/.bashrc; source $CBSUPPORT/lite_scripts/lite_cfg; cbviz $cbviz_opts" &
    done
}

set_defaults $*
get_options $*
sanity_check $*

start_visualization $*
