#!/bin/bash
# Copyright (C) 2008 University of Louisiana at Lafayette
# Authors: Mark McKelvy

script_name=`basename ${0}`

show_options(){
    #Add displayable options here
    echo
    echo "This script is used in the LITE venues for configuration
of common settings."
    echo
    echo "Usage: $script_name <options>"
    echo -e "\t[-p str]\t\t Arguments for litepackage script [$litepkg_opts]."
    echo -e "\t[-V str]\t\t Set LITE venue (flex, tis) [$venue]."
    echo
    exit
}

get_options(){
    #Catch arguments here
    while getopts "p:V:?" option; do
	case "$option" in
	    #Handle arguments here
	    p) litepkg_opts="$OPTARG";;
	    V) venue="$OPTARG";;
	    *) show_options;;
	esac
    done
}

set_defaults(){
    venue=$LITE_VENUE
    lite_scripts_path=/research/tools/lite/scripts

    literc=$lite_scripts_path/literc
    literc_opts=gcc.debug

    litepkg=$lite_scripts_path/litepackage
    litepkg_opts="vrjuggler 2.2.0"

    vj_cfg_path=$CBSUPPORT
}

sanity_check(){
    if [ "$venue" != "flex" -a \
	"$venue" != "tis" ] ; then
	echo "($script_name) error: incorrect venue set - $venue."
	exit -1
    fi
    
    if [ ! -d "$CBSUPPORT" ] ; then
	echo "($script_name) error: can't find cbsupport=$CBSUPPORT"
	exit -1
    fi

    if [ ! -d "$lite_scripts_path" ] ; then
	echo "($script_name) error: bad path to lite scripts - $lite_scripts_path"
	exit -1
    fi

    if [ ! -d "$vj_cfg_path" ] ; then
	echo "($script_name) error: bad path for vj_cfg - $vj_cfg_path"
	exit -1
    fi
}

source_lite_scripts(){
    if [ -f "$literc" ] ; then
	source $literc $literc_opts
    else
	echo "($script_name) warning: couldn't find $literc, skipping."
    fi

    if [ -f "$litepkg" ] ; then
	source $litepkg $litepkg_opts
    else
	echo "($script_name) warning: couldn't find $litepkg, skipping."
    fi
}

setup_vj_cfg_path(){
    link_path=`ls -l $CBSUPPORT | grep "lib -" | sed -e 's/ /\n/g' | tail -n 1`
    case "$venue" in
	flex)
	    if [ "$link_path" != "lib_ia64/" ] ; then
		cd $CBSUPPORT; unlink lib; ln -s lib_ia64 lib
		cd - >& /dev/null
	    fi
	    export VJ_CFG_PATH=$vj_cfg_path/multipipe;;
	tis)
	    export CB_DATA_NET=192.20.0.255:5000
	    if [ "$link_path" != "lib_x86_64/" ] ; then
		cd $CBSUPPORT; unlink lib; ln -s lib_x86_64 lib
		cd - >& /dev/null
	    fi
	    export VJ_CFG_PATH=$vj_cfg_path/cluster;;
	*) 
	    echo "($script_name) error: bad venue - $venue."
	    exit -1;;
    esac
}

set_defaults $*
get_options $*
sanity_check $*

source_lite_scripts
setup_vj_cfg_path

if [ ! -n "`echo $PATH | grep $VJ_BASE_DIR`" ] ; then
    export PATH=$PATH:$VJ_BASE_DIR/bin
fi

if [ ! -n "`echo $LD_LIBRARY_PATH | grep $VJ_BASE_DIR`" ] ; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VJ_BASE_DIR/lib:/research/tools/cppdom/current/linux.ia64.gcc.debug/lib:/research/tools/boost/current/linux.ia64.gcc.debug/lib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VJ_BASE_DIR/lib/vrjugglldd
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/usr/local/lib:/local/cbserver/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CBHOME/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/trackd/bin
export PATH=$PATH:$CBHOME/bin

export PRISM_COMPUTER=y

